# Generated by Django 4.2 on 2024-01-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'verbose_name': 'vehicles'},
        ),
    ]
