# Generated by Django 4.2 on 2024-01-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={},
        ),
    ]
