# Generated by Django 4.2 on 2024-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
