# Generated by Django 4.2 on 2024-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='mileage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
