# Generated by Django 4.2 on 2024-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicles_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
